### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by riyapannu7** [Kartik2016/Currency-Converter#3] opened 2017-10-11 05:57 UTC

**Comment by Kartikdot** [comment] 2017-10-12 07:03
Yes. Please update it. Do mention the API used as well as other features.

**Comment by shubham76** [comment] 2017-10-12 18:56
@Kartik2016 Please look into PR #6. Made changes as you mentioned including API description and other features.

**Comment by Kartikdot** [comment] 2017-10-13 09:15
Hi @shubham76. Before submitting any PR, you must go through the comments on the issue and also look out for the assigned tag to check if the issue is already assigned to someone. Also before starting your work on the issue, make a comment and ask if you can work on it or not since someone else might already be working on it. Since this issue was already assigned to @riyapannu7 and has already been resolved i cannot merge your PR. However, don't get disheartened. I will open new begginer friendly issues here soon with the hacktoberfest label. So do look out for that. Happy hacktoberfest ! Cheers.

**Comment by shubham76** [comment] 2017-10-13 17:42
Hey @Kartik2016! I am a newbie here in the Open Source world. Thank you for letting me know my mistakes. I'll surely keep in mind the points you mentioned. Thank you for helping out!

**Closed as completed** 2017-10-13 18:12 UTC
Labels: good-first issue, hacktoberfest
